# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: QC-FEM Oficial
email: quantum.c.Fem@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Grupo de estudiantes para estudiantes! Encuentra toda la información sobre nosotros aquí.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qc-fem.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  QC-FEM
instagram_username: QC-FEM
youtube_username: QC-FEM

# More fields for minima to custom website
# Default author for posts will be QC-FEM
author: QC-FEM

# Non-minima filds (not shipped with Jekyll)
# Add a copyright symbol
copyright: "QC-FEM"
# Logo-title path
title-logo: /images/website-title.png

# Build settings
# Removed minima theme since it is desirable to use a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
